FROM alpine:3.18

# Copy the bench.sh file into the container
COPY bench.sh /bin/bench.sh
COPY cobench /bin/cobench

# Make the bench.sh file executable
RUN chmod +x /bin/bench.sh
RUN chmod +x /bin/cobench

# Create user as non-root
RUN addgroup --g 1000 groupcontainer
RUN adduser -u 1000 -G groupcontainer -h /home/containeruser -D containeruser
 
# Set the user to use when running this image
USER containeruser

WORKDIR /typster
WORKDIR /samples
WORKDIR /data

# Set env for timeout
ENV TIMEOUT=1000

# Set the environment variables
ENV FILE_LIST=""
ENV WARMUP=3
ENV RUNS=30

# Run the bench.sh file
ENTRYPOINT [ "/bin/bench.sh" ]