FROM rust:1.71-alpine3.18

# Add the musl-dev package
RUN apk add --no-cache musl-dev

# Install the LLVM preview tools from cargo
RUN rustup component add llvm-tools-preview

# Copy the build.sh file into the container
COPY build.sh /bin/build.sh

# Make the build.sh file executable
RUN chmod +x /bin/build.sh

# Create user as non-root
RUN addgroup --g 1000 groupcontainer
RUN adduser -u 1000 -G groupcontainer -h /home/containeruser -D containeruser
 
# Set the user to use when running this image
USER containeruser

# set the working directory
WORKDIR /cargo

# Set the home for cargo
ENV CARGO_HOME=/cargo

# Set env for timeout
ENV TIMEOUT=400

# set the working directory
WORKDIR /data

# Run the build.sh file
ENTRYPOINT [ "/bin/build.sh" ]